-- The outbound half of the gateway (M17): enqueue is a member's act, dispatch
-- is an admin's, and a member never learns where a webhook points.

reset role;
set local role echo_app;

-- --- a member can discover subscriptions, and nothing else -----------------
select set_config('echo.actor_id', '02000000-0000-4000-8000-000000000002', true);

select t.ok(
  (select count(*) from echo.subscribed_webhooks('call.ready')) = 2,
  'a member sees both of the org''s subscriptions to an event');
select t.ok(
  (select count(*) from echo.subscribed_webhooks('call.ready') where not enabled) = 1,
  'including the disabled one, so the enqueuer can say what it is not sending');
select t.ok(
  (select count(*) from echo.subscribed_webhooks('nobody.subscribes')) = 0,
  'and nothing for an event no webhook wants');

-- The enqueuer must be able to name the identity the dispatcher will run as,
-- because the dispatcher cannot resolve it afterwards: reading
-- webhook.created_by needs the admin identity it is trying to obtain.
select t.ok(
  (select created_by from echo.subscribed_webhooks('call.ready')
    where webhook_id = '31000000-0000-4000-8000-000000000001')
    = '01000000-0000-4000-8000-000000000001',
  'a member learns who a webhook dispatches as — a colleague they can already see');
select t.ok(
  (select dispatchable from echo.subscribed_webhooks('call.ready')
    where webhook_id = '31000000-0000-4000-8000-000000000001'),
  'and that this one can still dispatch');

-- The whole point of the function: the row it is derived from stays invisible.
select t.ok((select count(*) from echo.webhook) = 0,
  'a member cannot read echo.webhook at all — not the url, not the secret, not the row');
select t.denied(
  $$insert into echo.webhook (org_id, url, secret_sha256, events, created_by)
    values ('0a000000-0000-4000-8000-00000000000a','https://evil.example.invalid',
            'x','{call.ready}','02000000-0000-4000-8000-000000000002')$$,
  'nor create one pointing wherever they like');

-- Org isolation holds through the helper, which is a definer function and so
-- the place a leak would actually happen.
select set_config('echo.actor_id', '05000000-0000-4000-8000-000000000005', true);
select t.ok(
  (select count(*) from echo.subscribed_webhooks('call.ready')) = 1,
  'the other org sees only its own subscription through the same function');
select set_config('echo.actor_id', '04000000-0000-4000-8000-000000000004', true);
select t.ok(
  (select count(*) from echo.subscribed_webhooks('call.ready')) = 0,
  'and a pending member sees none — the helper requires an active identity');

-- --- enqueue is a member's act, and a one-way one --------------------------
select set_config('echo.actor_id', '02000000-0000-4000-8000-000000000002', true);

insert into echo.webhook_delivery (id, org_id, webhook_id, event, payload)
values ('41000000-0000-4000-8000-000000000001', '0a000000-0000-4000-8000-00000000000a',
        '31000000-0000-4000-8000-000000000001', 'call.ready',
        '{"call_id":"c2000000-0000-4000-8000-000000000002"}');

select t.ok((select count(*) from echo.webhook_delivery) = 0,
  'the member records a delivery and cannot read it back — enqueue is write-only for them');

-- Which is why an enqueuer must supply the id rather than expect one:
-- RETURNING is subject to the select policy too.
select t.denied(
  $$insert into echo.webhook_delivery (org_id, webhook_id, event)
    values ('0a000000-0000-4000-8000-00000000000a',
            '31000000-0000-4000-8000-000000000001','call.ready')
    returning id$$,
  'RETURNING is refused for a member, so the delivery id has to be generated by the caller');

-- A delivery cannot name another org's webhook. Structural, not a policy —
-- the composite key makes it unrepresentable.
select t.denied(
  $$insert into echo.webhook_delivery (org_id, webhook_id, event)
    values ('0a000000-0000-4000-8000-00000000000a',
            '33000000-0000-4000-8000-000000000003','call.ready')$$,
  'and cannot aim a delivery at another org''s webhook');

-- --- dispatch is the admin's act -------------------------------------------
select set_config('echo.actor_id', '01000000-0000-4000-8000-000000000001', true);

select t.ok((select count(*) from echo.webhook_delivery) = 1,
  'the admin — who the dispatcher runs as — sees the queued delivery');
select t.ok(
  (select url is not null and secret_sha256 is not null from echo.webhook
    where id = '31000000-0000-4000-8000-000000000001'),
  'and can read where to send it and what signs it');

update echo.webhook_delivery
   set attempts = 1, response_code = 200, delivered_at = now()
 where id = '41000000-0000-4000-8000-000000000001';
select t.ok(
  (select delivered_at is not null from echo.webhook_delivery
    where id = '41000000-0000-4000-8000-000000000001'),
  'and records the outcome');

-- --- a member cannot advance one -------------------------------------------
-- This is what changed in 0026: the old policy let any active member update a
-- delivery, which described a dispatcher that the ruling replaced.
select set_config('echo.actor_id', '02000000-0000-4000-8000-000000000002', true);
select t.writes_nothing(
  $$update echo.webhook_delivery set response_code = 500
     where id = '41000000-0000-4000-8000-000000000001'$$,
  'a member cannot mark a delivery as anything — dispatch is not theirs');

-- --- a webhook whose registrar can no longer dispatch says so --------------
-- The dispatcher fails closed when its identity has been demoted, which is
-- correct but silent and late. Surfacing it at enqueue time is the same
-- forfeit-out-loud shape as returning disabled subscriptions.
reset role;
insert into echo.webhook (id, org_id, url, secret_sha256, events, enabled, created_by)
values ('34000000-0000-4000-8000-000000000004', '0a000000-0000-4000-8000-00000000000a',
        'https://hooks.example.invalid/orphan', 'sha-hook-orphan', '{call.ready}', true,
        '02000000-0000-4000-8000-000000000002');   -- bob: a member, not an admin

set local role echo_app;
select set_config('echo.actor_id', '02000000-0000-4000-8000-000000000002', true);
select t.ok(
  (select dispatchable from echo.subscribed_webhooks('call.ready')
    where webhook_id = '34000000-0000-4000-8000-000000000004') = false,
  'a subscription whose registrar is not an active admin reports itself undispatchable');
select t.ok(
  (select count(*) from echo.subscribed_webhooks('call.ready')) = 3,
  'and is still returned, not hidden — the enqueuer decides what to say about it');

-- --- registering binds the webhook to the registrar (0030) -----------------
-- created_by is not merely a record of who added it: under M17 it is the
-- identity the dispatcher runs as. Supplying someone else's name would hand
-- them outbound authority they never agreed to.
select set_config('echo.actor_id', '01000000-0000-4000-8000-000000000001', true);
select t.denied(
  $$insert into echo.webhook (org_id, url, secret_sha256, events, created_by)
    values ('0a000000-0000-4000-8000-00000000000a','https://hooks.example.invalid/x',
            'sha-x','{call.ready}','02000000-0000-4000-8000-000000000002')$$,
  'an admin cannot register a webhook that dispatches as someone else');

insert into echo.webhook (id, org_id, url, secret_sha256, events, created_by)
values ('35000000-0000-4000-8000-000000000005', '0a000000-0000-4000-8000-00000000000a',
        'https://hooks.example.invalid/mine', 'sha-mine', '{call.ready}',
        '01000000-0000-4000-8000-000000000001');
select t.ok(
  (select created_by from echo.webhook where id = '35000000-0000-4000-8000-000000000005')
    = '01000000-0000-4000-8000-000000000001',
  'registering under their own name is the only way in');

-- Binding creation would be pointless if an edit could reassign it after.
select t.denied(
  $$update echo.webhook set created_by = '02000000-0000-4000-8000-000000000002'
     where id = '35000000-0000-4000-8000-000000000005'$$,
  'and the registrar cannot be reassigned afterwards — re-register instead');

-- Managing stays any-admin, so a departed creator strands nothing.
update echo.webhook set enabled = false
 where id = '31000000-0000-4000-8000-000000000001';
select t.ok(
  (select not enabled from echo.webhook where id = '31000000-0000-4000-8000-000000000001'),
  'any admin may still disable any of the org''s webhooks');

-- --- and the agent is nowhere near any of this -----------------------------
reset role;
set local role echo_agent;
select set_config('echo.actor_id', '01000000-0000-4000-8000-000000000001', true);
select t.denied($$select * from echo.webhook_delivery$$,
  'the agent cannot see deliveries');
select t.denied($$select echo.subscribed_webhooks('call.ready')$$,
  'nor call the subscription helper — it has no execute grant on it');

reset role;
